name: BedWars1058-TeamSelector
author: batmann4bot
version: ${project.version}
description: Team Selector Add-on for BedWars2023 Minigame.
website: https://andrei1058.dev
main: com.tomkeuper.bedwars.teamselector.Main
softdepend: [BedWars2023]
api-version: '1.13'